[MFLOG|0|2024-10-19T21:54:37.098428Z|runtime|1eadff19-a414-49d8-a914-7c73c8b1ac97]    Internal error
[MFLOG|0|2024-10-19T21:54:37.099871Z|runtime|1f2f7d3c-580d-4819-96f1-da324a4b966b]Traceback (most recent call last):
[MFLOG|0|2024-10-19T21:54:37.099935Z|runtime|08077f63-1a66-4d24-85e2-22fac5d506c3]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/cli.py", line 1139, in main
[MFLOG|0|2024-10-19T21:54:37.099970Z|runtime|7e86bb9d-9354-42b6-ab9e-cdbb9501d347]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2024-10-19T21:54:37.100006Z|runtime|e485d828-8afe-4d58-988b-576392a81668]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2024-10-19T21:54:37.100062Z|runtime|83fbe452-c319-4475-b596-4e7cc34fc011]    return func(args, kwargs)
[MFLOG|0|2024-10-19T21:54:37.657456Z|runtime|d60609ab-133b-478d-8a5f-c184fd5f4986]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.657708Z|runtime|b34cd79a-511b-480b-8131-d3e2f12a7c6e]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2024-10-19T21:54:37.657744Z|runtime|807114e0-49b8-4de0-a513-dd1807a6ab27]    return self.main(args, kwargs)
[MFLOG|0|2024-10-19T21:54:37.657773Z|runtime|723f5b9a-dd94-4617-94e3-0f0e1083736c]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.657798Z|runtime|21187572-bf38-4306-8592-5ed504ec3c3b]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2024-10-19T21:54:37.657821Z|runtime|320f511d-6a4c-4d2e-aa1f-98c00f3c8a06]    rv = self.invoke(ctx)
[MFLOG|0|2024-10-19T21:54:37.657842Z|runtime|62694fd9-23c6-43e6-bf67-1037380d308d]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.657864Z|runtime|64637981-e72f-4c26-93d9-41de835489b4]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2024-10-19T21:54:37.657944Z|runtime|463d32eb-7f51-4873-8d9d-eff6b187b804]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2024-10-19T21:54:37.657967Z|runtime|489a9f85-09f4-4337-b436-595cf7c48e4c]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.657987Z|runtime|af30ee6f-b1c7-4c19-bf11-b59bd73b0823]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2024-10-19T21:54:37.658006Z|runtime|9cc79026-b435-48c3-b6fa-75636a3c90ca]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2024-10-19T21:54:37.658026Z|runtime|a3f3f172-fe1f-4b30-995c-c1728d4eef7d]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.658045Z|runtime|bb92f8fb-fb16-44f5-83a7-7aed0e264c97]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2024-10-19T21:54:37.658470Z|runtime|c9b2ccc8-831f-46b2-a754-7c05c7b49d3b]    return callback(args, kwargs)
[MFLOG|0|2024-10-19T21:54:37.658492Z|runtime|be9f54ee-edf7-4a21-86b3-59137742db88]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.658511Z|runtime|85241d1e-fd5f-4166-af96-ba26091ac1eb]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2024-10-19T21:54:37.658531Z|runtime|bb5d62ed-c3f6-46bc-b2cc-7dd98c1aa4f7]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2024-10-19T21:54:37.658550Z|runtime|89305aa5-155f-458a-aff4-5e40d09180dc]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.658569Z|runtime|32b8cfb2-97d5-4d98-b835-136cae352e62]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/cli.py", line 469, in step
[MFLOG|0|2024-10-19T21:54:37.658724Z|runtime|acf7ee85-7cfd-4cac-9134-74f36c7bfe77]    task.run_step(
[MFLOG|0|2024-10-19T21:54:37.658746Z|runtime|208cb52b-1e11-4d8b-ae98-8f8c086a9104]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/task.py", line 729, in run_step
[MFLOG|0|2024-10-19T21:54:37.658766Z|runtime|2a507881-5a76-44ac-80da-4c0df7504fad]    output.persist(self.flow)
[MFLOG|0|2024-10-19T21:54:37.658786Z|runtime|14479854-72f6-4c36-bcc4-711b0b4125d2]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/task_datastore.py", line 31, in method
[MFLOG|0|2024-10-19T21:54:37.658805Z|runtime|d3372fe8-82d2-4231-b9ad-93ad457dc4f8]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T21:54:37.658825Z|runtime|3acfb330-a6bf-4423-bc0d-58edbce9784f]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.659730Z|runtime|67064beb-a1d6-4f6c-9430-e03c421efa67]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/task_datastore.py", line 45, in method
[MFLOG|0|2024-10-19T21:54:37.659754Z|runtime|f1e7f25b-c8b3-4e00-a6d2-d2845758f738]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T21:54:37.659773Z|runtime|987afe7d-436d-4adb-b4b6-f776c65e19f7]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.659792Z|runtime|27e4e98e-72d9-4958-996c-6beafbd97f6b]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/task_datastore.py", line 744, in persist
[MFLOG|0|2024-10-19T21:54:37.659811Z|runtime|5233726b-91dc-43ae-b365-a60a7cb08776]    self.save_artifacts(artifacts_iter(), len_hint=len(valid_artifacts))
[MFLOG|0|2024-10-19T21:54:37.659829Z|runtime|ad76b4c1-051c-4f3b-a29f-d45e4ed02224]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/task_datastore.py", line 31, in method
[MFLOG|0|2024-10-19T21:54:37.659848Z|runtime|94baa716-68ac-45d4-9eed-58a9b165c1ff]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T21:54:37.659868Z|runtime|be878ad8-187c-4fae-8f1c-967b024a4225]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.659887Z|runtime|d308c42c-da45-43b5-a4f1-1b2a1c45dd30]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/task_datastore.py", line 45, in method
[MFLOG|0|2024-10-19T21:54:37.659906Z|runtime|d49f6b32-26a9-4efb-b558-02444e5808b0]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T21:54:37.659924Z|runtime|1c640f4f-abe2-420f-a145-5d0928decaa8]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.660165Z|runtime|a521b5f6-8659-4f05-b71f-3df6714355cf]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/task_datastore.py", line 329, in save_artifacts
[MFLOG|0|2024-10-19T21:54:37.660187Z|runtime|3a550176-0f2b-4804-83ab-50e7d6f2f242]    save_result = self._ca_store.save_blobs(pickle_iter(), len_hint=len_hint)
[MFLOG|0|2024-10-19T21:54:37.660206Z|runtime|4000c012-521a-4f53-bb16-91e0c2d66ad3]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.660224Z|runtime|f4a8e5f9-924a-4b2e-91da-cd7fce316804]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/content_addressed_store.py", line 100, in save_blobs
[MFLOG|0|2024-10-19T21:54:37.660243Z|runtime|1de5ace9-72d8-442f-bcf7-5dc91e29814e]    self._storage_impl.save_bytes(packing_iter(), overwrite=True, len_hint=len_hint)
[MFLOG|0|2024-10-19T21:54:37.660442Z|runtime|366c716f-1f80-471c-a0ed-9e3c28b4dbcc]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/plugins/datastores/local_storage.py", line 107, in save_bytes
[MFLOG|0|2024-10-19T21:54:37.660465Z|runtime|3950c1c2-e633-4667-95ca-3100c391b662]    for path, obj in path_and_bytes_iter:
[MFLOG|0|2024-10-19T21:54:37.660484Z|runtime|4462eb03-8b95-4a05-a0de-588f58d2128f]                     ^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.660503Z|runtime|d077f8db-9600-4992-91ee-e79461d0e130]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/content_addressed_store.py", line 78, in packing_iter
[MFLOG|0|2024-10-19T21:54:37.660522Z|runtime|dee2d0dc-2508-4dbf-a205-bb722127cb2a]    for blob in blob_iter:
[MFLOG|0|2024-10-19T21:54:37.660541Z|runtime|6d1513e5-26b2-4460-982c-d0dc827a3800]                ^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.660575Z|runtime|70aad3a8-f1a5-4b38-8caa-ea3f7bb67873]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/datastore/task_datastore.py", line 302, in pickle_iter
[MFLOG|0|2024-10-19T21:54:37.660596Z|runtime|da622528-ddf6-4b55-ad1b-54990ccd6cfa]    blob = pickle.dumps(obj, protocol=2)
[MFLOG|0|2024-10-19T21:54:37.660618Z|runtime|cf3f6872-ce09-4eb7-a3c4-3849460f2c43]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.660637Z|runtime|fb09000a-4d2c-4960-a6a7-67e9bc438647]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/tensorflow/python/framework/ops.py", line 327, in __reduce__
[MFLOG|0|2024-10-19T21:54:37.660657Z|runtime|790d1534-0611-404b-bcfa-1c9f8888aa24]    return convert_to_tensor, (self._numpy(),)
[MFLOG|0|2024-10-19T21:54:37.660675Z|runtime|556b2878-1811-455f-9360-616dcc660e5d]                               ^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.660867Z|runtime|fd21e41e-293e-4f2e-ac5f-f9f328d1f26c]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/tensorflow/python/framework/ops.py", line 375, in _numpy
[MFLOG|0|2024-10-19T21:54:37.660888Z|runtime|42de5d01-d30a-4b83-9e6b-db9bfd3a0721]    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
[MFLOG|0|2024-10-19T21:54:37.660908Z|runtime|ba7e9230-79e5-4533-8c5d-0cfced33fafe]    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:54:37.660927Z|runtime|6b83c0d3-a346-4fd6-a83f-286dfc8ec46f]tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot convert a Tensor of dtype variant to a NumPy array.
[MFLOG|0|2024-10-19T21:54:37.660947Z|runtime|b4273d97-32ab-4f8e-8ada-ba0b7d041738]
[MFLOG|0|2024-10-19T21:54:37.661587Z|runtime|e8636bdd-a01f-4a87-90f2-151aa8948324]Task failed.